# version: '3.8'

# services:
#   mssql_paises:
#     image: leandroexp/imgdbpaises:v1.0
#     container_name: mssql_paises_container
#     ports:
#       - "666:1433"

#   mssql_idiomas:
#     image: leandroexp/imgdbidiomas:v1.0
#     container_name: mssql_idiomas_container
#     ports:
#       - "667:1433"

#   arquitecturag1:
#     image: leandroexp/serverpaisesidiomas:v1.0
#     container_name: arquitecturag1_container
#     ports:
#       - "8080:8080"

version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - arquitecturag1
    restart: always

  mssql_paises:
    image: leandroexp/imgdbpaises:v1.0
    restart: always

  mssql_idiomas:
    image: leandroexp/imgdbidiomas:v1.0
    restart: always

  arquitecturag1:
    image: leandroexp/serverpaisesidiomas:v1.0
    restart: always

