version: '3.8'

services:
  mssql_paises:
    image: leandroexp/imgdbpaises:v1.0
    container_name: mssql_paises_container
    ports:
      - "666:1433"

  mssql_idiomas:
    image: leandroexp/imgdbidiomas:v1.0
    container_name: mssql_idiomas_container
    ports:
      - "667:1433"

  arquitecturag1:
    image: leandroexp/serverpaisesidiomas:v1.0
    container_name: arquitecturag1_container
    ports:
      - "8080:8080"